version: '3.7'
services:
   client:
      build:
         context: ./Front-End
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./Front-End:/app
         - /app/node_modules
