version: '3.7'
services:

    mongodb:
        image: mongo
        container_name: sl-mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: smart-ledger
            MONGODB_DATA_DIR: /data/db
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

    api:
        image: sl-api
        container_name: sl-api
        build:
            context: ./Back-End
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            DEBUG: "true"
        volumes:
            - appdata:/var/www/
        depends_on:
            - mongodb
        networks:
            - frontend
            - backend

    client:
        image: sl-client
        container_name: sl-client
        build:
            context: ./Front-End
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ./Front-End:/app
            - node_modules:/app/node_modules
        networks:
            - frontend
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - api

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local
    node_modules:
        driver: local
