version: '3.7'
services:

   mongodb:
      image: mongo
      container_name: smart_ledger_mongo
      restart: unless-stopped
      command: mongod --auth
      environment:
         MONGO_INITDB_ROOT_USERNAME: "admin"
         MONGO_INITDB_ROOT_PASSWORD: "password"
         MONGO_INITDB_DATABASE: smart-ledger
         MONGODB_DATA_DIR: /data/db
      volumes:
         - mongodbdata:/data/db
      networks:
         - backend

   api:
      image: smart_ledger_api
      container_name: smart_ledger_api
      build:
         context: ./Back-End
         dockerfile: Dockerfile
      ports:
         - "5000:5000"
      environment:
         MONGO_HOST: mongodb
         API_USERNAME: "apiuser"
         API_PASSWORD: "apipassword"
      volumes:
         - appdata:/var/www/
      depends_on:
         - mongodb
      networks:
         - frontend
         - backend

   client:
      image: smart_ledger_client
      container_name: smart_ledger_client
      build:
         context: ./Front-End
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./Front-End:/app
         - node_modules:/app/node_modules
      networks:
         - frontend
      environment:
         - CHOKIDAR_USEPOLLING=true
      depends_on:
         - api

networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge
volumes:
   mongodbdata:
      driver: local
   appdata:
      driver: local
   node_modules:
      driver: local
