version: '3.7'
services:
   client:
      image: smart-ledger-client
      container_name: smart-ledger-client
      build:
         context: ./Front-End
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./Front-End:/app
      networks:
         - frontend
      environment:
         - CHOKIDAR_USEPOLLING=true
   
   mongodb:
      image: mongo
      container_name: smart-ledger-mongo
      restart: unless-stopped
      command: mongod --auth
      environment:
         MONGO_INITDB_ROOT_USERNAME: "admin"
         MONGO_INITDB_ROOT_PASSWORD: "password"
         MONGO_INITDB_DATABASE: smart-ledger
         MONGODB_DATA_DIR: /data/db
      volumes:
         - mongodbdata:/data/db
      networks:
         - backend

   api:
      image: smart-ledger-api
      container_name: smart-ledger-api
      build:
         context: ./Back-End
         dockerfile: Dockerfile
         args:
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "apiuser"
            MONGODB_PASSWORD: "apipassword"

      command: gunicorn --bind 0.0.0.0:5000 app:app
      ports:
         - "5000:5000"
      environment:
         MONGODB_HOST: mongodb
         MONGODB_USERNAME: "apiuser"
         MONGODB_PASSWORD: "apipassword"
      volumes:
         - appdata:/var/www/
      depends_on:
         - mongodb
      networks:
         - frontend
         - backend
networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge
volumes:
   mongodbdata:
      driver: local
   appdata:
      driver: local
