version: '3.7'
services:

    mongodb:
        container_name: sl-mongo
    api:
        container_name: sl-api
        build:
            context: ./Back-End
        environment:
            DEBUG: "false"
    client:
        container_name: sl-client
        build:
            context: ./Front-End
            dockerfile: Dockerfile-prod
        ports:
            - "80:80"
