name: Deploy-to-EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Action
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /opt/Smart-Ledger &&
            git reset --hard HEAD &&
            git checkout main &&
            git pull &&
            sudo ./deploy.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
