name: Deploy-to-EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Action
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.REPO_PATH }}
            ls
#            sudo ./deploy.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY}}
